export const SET_ADDRESS = "SET_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const SET_MARKETPLACE_CONTRACT = "SET_MARKETPLACE_CONTRACT"
export const GET_MARKETPLACE_CONTRACT = "GET_MARKETPLACE_CONTRACT"
export const SET_USER_CONTRACT = "SET_USER_CONTRACT"
export const GET_USER_CONTRACT = "GET_USER_CONTRACT"
export const SET_USER_INFO = "SET_USER_INFO";
export const GET_USER_INFO = "GET_USER_INFO";
