export const SET_ADDRESS = "SET_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const SET_MARKETPLACE_CONTRACT = "SET_MARKETPLACE_CONTRACT"
export const GET_MARKETPLACE_CONTRACT = "GET_MARKETPLACE_CONTRACT"
